### ISSUE TITLE
Harden ByzCoin

### ISSUE THREAD

**Issue by ineiti** [c4dt/byzcoin#14]
The following issues should be implemented to harden byzcoin:
- [x] dedis/cothority#2204 / dedis/onet#620 - Amplification attack: limit access to node-node communication
- [ ] dedis/cothority#2205 - block flooding: validity checks for ClientTransactions
- [ ] dedis/cothority#2207 - flooding and CPU exhaustion: limit service endpoints
- [x] dedis/cothority#2206 - cleanup: simplify BEVM contracts
- [x] #12 - lesser attack surface: remove calypso protocol
- [x] #13 - lesser attack surface: disable blscosi protocol
